blank_issues_enabled: false
contact_links:
  - name: CurseForge Comments
    url: https://www.curseforge.com/wow/addons/minimaporganizer
    about: For general questions or feedback, use CurseForge comments
